version: '3'
services:
  server:
    container_name: server
    build:
      context: .
    volumes:
      - servervol:/serverdata
    networks:
      - backend
      - proxy

networks:
  backend: {}
  proxy:
    name: proxy_network

volumes:
  servervol:
    name: servervol
