version: '3'
services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - 8080:5000
    volumes:
      - servervol:/serverdata
    networks:
      - backend

networks:
  backend: {}

volumes:
  servervol: {}
