version: '3'
services:
  server:
    container_name: server
    image: ${IMAGE_TAG}
    ports:
      - 5000:5000
    volumes:
      - servervol:/serverdata
    networks:
      - backend

networks:
  backend: {}

volumes:
  servervol: {}
